export const strings = {
    en: {
        app_name: "Spliitz",
        tagline: "Split expenses with friends and family",
        login_title: "Sign In",
        signup_title: "Create Account",
        email_placeholder: "Email",
        password_placeholder: "Password",
        confirm_password_placeholder: "Confirm Password",
        username_placeholder: "Username",
        first_name_placeholder: "First Name",
        last_name_placeholder: "Last Name",
        phone_placeholder: "Phone (Optional)",
        login_button: "Sign In",
        signup_button: "Sign Up",
        forgot_password: "Forgot Password?",
        dont_have_account: "Don't have an account?",
        already_have_account: "Already have an account?",
        signup_link: "Sign Up",
        login_link: "Log In",
        about_us: "About Us",
        contact_us: "Contact Us",
        back_to_signin: "← Back to Sign In",
        dashboard_title: "Dashboard",
        groups_title: "Groups",
        friends_title: "Friends",
        activity_title: "Activity",
        profile_title: "Profile",
        settle_up: "Settle Up",
        add_expense: "Add Expense",
        save: "Save",
        cancel: "Cancel",
        delete: "Delete",
        edit: "Edit",
        logout: "Log Out",
        success: "Success",
        error: "Error",
        loading: "Loading...",
        expense_added: "Expense added successfully",
        group_created: "Group created successfully",
        friend_added: "Friend added successfully",
        profile_updated: "Profile updated successfully"
    },
    "zh-Hans": {
        app_name: "Spliitz",
        tagline: "与亲友分摊在开销",
        login_title: "登录",
        signup_title: "创建账户",
        email_placeholder: "电子邮件",
        password_placeholder: "密码",
        confirm_password_placeholder: "确认密码",
        username_placeholder: "用户名",
        first_name_placeholder: "名字",
        last_name_placeholder: "姓氏",
        phone_placeholder: "电话 (可选)",
        login_button: "登录",
        signup_button: "注册",
        forgot_password: "忘记密码？",
        dont_have_account: "还没有账户？",
        already_have_account: "已有账户？",
        signup_link: "注册",
        login_link: "登录",
        about_us: "关于我们",
        contact_us: "联系我们",
        back_to_signin: "← 返回登录",
        dashboard_title: "仪表板",
        groups_title: "群组",
        friends_title: "好友",
        activity_title: "活动",
        profile_title: "个人资料",
        settle_up: "结清",
        add_expense: "添加费用",
        save: "保存",
        cancel: "取消",
        delete: "删除",
        edit: "编辑",
        logout: "退出登录",
        success: "成功",
        error: "错误",
        loading: "加载中...",
        expense_added: "费用添加成功",
        group_created: "群组创建成功",
        friend_added: "好友添加成功",
        profile_updated: "个人资料更新成功"
    },
    "zh-Hant": {
        app_name: "Spliitz",
        tagline: "與親友分攤開銷",
        login_title: "登入",
        signup_title: "建立帳戶",
        email_placeholder: "電子郵件",
        password_placeholder: "密碼",
        confirm_password_placeholder: "確認密碼",
        username_placeholder: "使用者名稱",
        first_name_placeholder: "名字",
        last_name_placeholder: "姓氏",
        phone_placeholder: "電話 (可選)",
        login_button: "登入",
        signup_button: "註冊",
        forgot_password: "忘記密碼？",
        dont_have_account: "還沒有帳戶？",
        already_have_account: "已有帳戶？",
        signup_link: "註冊",
        login_link: "登入",
        about_us: "關於我們",
        contact_us: "聯繫我們",
        back_to_signin: "← 返回登入",
        dashboard_title: "儀表板",
        groups_title: "群組",
        friends_title: "好友",
        activity_title: "活動",
        profile_title: "個人資料",
        settle_up: "結清",
        add_expense: "添加費用",
        save: "保存",
        cancel: "取消",
        delete: "刪除",
        edit: "編輯",
        logout: "登出",
        success: "成功",
        error: "錯誤",
        loading: "載入中...",
        expense_added: "費用添加成功",
        group_created: "群組創建成功",
        friend_added: "好友添加成功",
        profile_updated: "個人資料更新成功"
    },
    hi: {
        app_name: "Spliitz",
        tagline: "दोस्तों और परिवार के साथ खर्च बांटें",
        login_title: "लॉग इन करें",
        signup_title: "खाता बनाएं",
        email_placeholder: "ईमेल",
        password_placeholder: "पासवर्ड",
        confirm_password_placeholder: "पासवर्ड की पुष्टि करें",
        username_placeholder: "उपयोगकर्ता नाम",
        first_name_placeholder: "पहला नाम",
        last_name_placeholder: "उपनाम",
        phone_placeholder: "फ़ोन (वैकल्पिक)",
        login_button: "लॉग इन करें",
        signup_button: "साइन अप करें",
        forgot_password: "पासवर्ड भूल गए?",
        dont_have_account: "खाता नहीं है?",
        already_have_account: "क्या आपके पास पहले से एक खाता मौजूद है?",
        signup_link: "साइन अप करें",
        login_link: "लॉग इन करें",
        about_us: "हमारे बारे में",
        contact_us: "संपर्क करें",
        back_to_signin: "← साइन इन पर वापस जाएं",
        dashboard_title: "डैशबोर्ड",
        groups_title: "समूह",
        friends_title: "दोस्तों",
        activity_title: "गतिविधि",
        profile_title: "प्रोफ़ाइल",
        settle_up: "हिसाब बराबर करें",
        add_expense: "खर्च जोड़ें",
        save: "सहेजें",
        cancel: "रद्द करें",
        delete: "हटाएं",
        edit: "संपादित करें",
        logout: "लॉग आउट",
        success: "सफलता",
        error: "त्रुटि",
        loading: "लोड हो रहा है...",
        expense_added: "खर्च सफलतापूर्वक जोड़ा गया",
        group_created: "समूह सफलतापूर्वक बनाया गया",
        friend_added: "दोस्त सफलतापूर्वक जोड़ा गया",
        profile_updated: "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई"
    },
    es: {
        app_name: "Spliitz",
        tagline: "Divide gastos con amigos y familia",
        login_title: "Iniciar sesión",
        signup_title: "Crear cuenta",
        email_placeholder: "Correo electrónico",
        password_placeholder: "Contraseña",
        confirm_password_placeholder: "Confirmar contraseña",
        username_placeholder: "Nombre de usuario",
        first_name_placeholder: "Nombre",
        last_name_placeholder: "Apellido",
        phone_placeholder: "Teléfono (Opcional)",
        login_button: "Iniciar sesión",
        signup_button: "Registrarse",
        forgot_password: "¿Olvidaste tu contraseña?",
        dont_have_account: "¿No tienes cuenta?",
        already_have_account: "¿Ya tienes cuenta?",
        signup_link: "Registrarse",
        login_link: "Iniciar sesión",
        about_us: "Sobre nosotros",
        contact_us: "Contáctanos",
        back_to_signin: "← Volver a inicio de sesión",
        dashboard_title: "Tablero",
        groups_title: "Grupos",
        friends_title: "Amigos",
        activity_title: "Actividad",
        profile_title: "Perfil",
        settle_up: "Saldar deudas",
        add_expense: "Añadir gasto",
        save: "Guardar",
        cancel: "Cancelar",
        delete: "Eliminar",
        edit: "Editar",
        logout: "Cerrar sesión",
        success: "Éxito",
        error: "Error",
        loading: "Cargando...",
        expense_added: "Gasto añadido con éxito",
        group_created: "Grupo creado con éxito",
        friend_added: "Amigo añadido con éxito",
        profile_updated: "Perfil actualizado con éxito"
    },
    fr: {
        app_name: "Spliitz",
        tagline: "Partagez les frais avec vos amis et votre famille",
        login_title: "Se connecter",
        signup_title: "Créer un compte",
        email_placeholder: "E-mail",
        password_placeholder: "Mot de passe",
        confirm_password_placeholder: "Confirmer le mot de passe",
        username_placeholder: "Nom d'utilisateur",
        first_name_placeholder: "Prénom",
        last_name_placeholder: "Nom",
        phone_placeholder: "Téléphone (Facultatif)",
        login_button: "Se connecter",
        signup_button: "S'inscrire",
        forgot_password: "Mot de passe oublié ?",
        dont_have_account: "Pas encore de compte ?",
        already_have_account: "Vous avez déjà un compte ?",
        signup_link: "S'inscrire",
        login_link: "Se connecter",
        about_us: "À propos",
        contact_us: "Contactez-nous",
        back_to_signin: "← Retour à la connexion",
        dashboard_title: "Tableau de bord",
        groups_title: "Groupes",
        friends_title: "Amis",
        activity_title: "Activité",
        profile_title: "Profil",
        settle_up: "Régler",
        add_expense: "Ajouter une dépense",
        save: "Enregistrer",
        cancel: "Annuler",
        delete: "Supprimer",
        edit: "Modifier",
        logout: "Se déconnecter",
        success: "Succès",
        error: "Erreur",
        loading: "Chargement...",
        expense_added: "Dépense ajoutée avec succès",
        group_created: "Groupe créé avec succès",
        friend_added: "Ami ajouté avec succès",
        profile_updated: "Profil mis à jour avec succès"
    },
    ar: {
        app_name: "Spliitz",
        tagline: "تقاسم المصاريف مع الأصدقاء والعائلة",
        login_title: "تسجيل الدخول",
        signup_title: "إنشاء حساب",
        email_placeholder: "البريد الإلكتروني",
        password_placeholder: "كلمة المرور",
        confirm_password_placeholder: "تأكيد كلمة المرور",
        username_placeholder: "اسم المستخدم",
        first_name_placeholder: "الاسم الأول",
        last_name_placeholder: "اسم العائلة",
        phone_placeholder: "الهاتف (اختياري)",
        login_button: "تسجيل الدخول",
        signup_button: "تسجيل",
        forgot_password: "هل نسيت كلمة المرور؟",
        dont_have_account: "ليس لديك حساب؟",
        already_have_account: "لدي حساب بالفعل؟",
        signup_link: "تسجيل",
        login_link: "تسجيل الدخول",
        about_us: "معلومات عنا",
        contact_us: "اتصل بنا",
        back_to_signin: "← العودة لتسجيل الدخول",
        dashboard_title: "لوحة القيادة",
        groups_title: "مجموعات",
        friends_title: "أصدقاء",
        activity_title: "نشاط",
        profile_title: "الملف الشخصي",
        settle_up: "تصفية الحساب",
        add_expense: "إضافة مصروف",
        save: "حفظ",
        cancel: "إلغاء",
        delete: "حذف",
        edit: "تعديل",
        logout: "تسجيل الخروج",
        success: "تم بنجاح",
        error: "خطأ",
        loading: "جار التحميل...",
        expense_added: "تم إضافة المصروف بنجاح",
        group_created: "تم إنشاء المجموعة بنجاح",
        friend_added: "تم إضافة الصديق بنجاح",
        profile_updated: "تم تحديث الملف الشخصي بنجاح"
    },
    bn: {
        app_name: "Spliitz",
        tagline: "বন্ধুবান্ধব এবং পরিবারের সাথে খরচ ভাগ করুন",
        login_title: "লগ ইন",
        signup_title: "অ্যাকাউন্ট তৈরি করুন",
        email_placeholder: "ইমেল",
        password_placeholder: "পাসওয়ার্ড",
        confirm_password_placeholder: "পাসওয়ার্ড নিশ্চিত করুন",
        username_placeholder: "ব্যবহারকারীর নাম",
        first_name_placeholder: "নামের প্রথম অংশ",
        last_name_placeholder: "নামের শেষাংশ",
        phone_placeholder: "ফোন (ঐচ্ছিক)",
        login_button: "লগ ইন",
        signup_button: "সাইন আপ",
        forgot_password: "পাসওয়ার্ড ভুলে গেছেন?",
        dont_have_account: "অ্যাকাউন্ট নেই?",
        already_have_account: "ইতিমধ্যে একটি অ্যাকাউন্ট আছে?",
        signup_link: "সাইন আপ",
        login_link: "লগ ইন",
        about_us: "আমাদের সম্পর্কে",
        contact_us: "যোগাযোগ করুন",
        back_to_signin: "← সাইন ইন এ ফিরে যান",
        dashboard_title: "ড্যাশবোর্ড",
        groups_title: "গ্রুপ",
        friends_title: "বন্ধু",
        activity_title: "কার্যকলাপ",
        profile_title: "প্রোফাইল",
        settle_up: "নিষ্পত্তি",
        add_expense: "ব্যয় যোগ করুন",
        save: "সংরক্ষণ করুন",
        cancel: "বাতিল করুন",
        delete: "মুছে ফেলুন",
        edit: "সম্পাদনা করুন",
        logout: "লগ আউট",
        success: "সফল",
        error: "ত্রুটি",
        loading: "লোড হচ্ছে...",
        expense_added: "ব্যয় সফলভাবে যোগ করা হয়েছে",
        group_created: "গ্রুপ সফলভাবে তৈরি করা হয়েছে",
        friend_added: "বন্ধু সফলভাবে যোগ করা হয়েছে",
        profile_updated: "প্রোফাইল সফলভাবে আপডেট করা হয়েছে"
    },
    pt: {
        app_name: "Spliitz",
        tagline: "Divida despesas com amigos e família",
        login_title: "Entrar",
        signup_title: "Criar conta",
        email_placeholder: "E-mail",
        password_placeholder: "Senha",
        confirm_password_placeholder: "Confirmar senha",
        username_placeholder: "Nome de usuário",
        first_name_placeholder: "Nome",
        last_name_placeholder: "Sobrenome",
        phone_placeholder: "Telefone (Opcional)",
        login_button: "Entrar",
        signup_button: "Inscrever-se",
        forgot_password: "Esqueceu a senha?",
        dont_have_account: "Não tem conta?",
        already_have_account: "Já tem uma conta?",
        signup_link: "Inscrever-se",
        login_link: "Entrar",
        about_us: "Sobre nós",
        contact_us: "Contate-nos",
        back_to_signin: "← Voltar para Login",
        dashboard_title: "Painel",
        groups_title: "Grupos",
        friends_title: "Amigos",
        activity_title: "Atividade",
        profile_title: "Perfil",
        settle_up: "Quitar débitos",
        add_expense: "Adicionar despesa",
        save: "Salvar",
        cancel: "Cancelar",
        delete: "Excluir",
        edit: "Editar",
        logout: "Sair",
        success: "Sucesso",
        error: "Erro",
        loading: "Carregando...",
        expense_added: "Despesa adicionada com sucesso",
        group_created: "Grupo criado com sucesso",
        friend_added: "Amigo adicionado com sucesso",
        profile_updated: "Perfil atualizado com sucesso"
    },
    ru: {
        app_name: "Spliitz",
        tagline: "Делите расходы с друзьями и семьей",
        login_title: "Войти",
        signup_title: "Создать аккаунт",
        email_placeholder: "Email",
        password_placeholder: "Пароль",
        confirm_password_placeholder: "Подтвердите пароль",
        username_placeholder: "Имя пользователя",
        first_name_placeholder: "Имя",
        last_name_placeholder: "Фамилия",
        phone_placeholder: "Телефон (необязательно)",
        login_button: "Войти",
        signup_button: "Регистрация",
        forgot_password: "Забыли пароль?",
        dont_have_account: "Нет аккаунта?",
        already_have_account: "Уже есть аккаунт?",
        signup_link: "Регистрация",
        login_link: "Войти",
        about_us: "О нас",
        contact_us: "Связаться с нами",
        back_to_signin: "← Назад ко входу",
        dashboard_title: "Панель",
        groups_title: "Группы",
        friends_title: "Друзья",
        activity_title: "Активность",
        profile_title: "Профиль",
        settle_up: "Рассчитаться",
        add_expense: "Добавить расход",
        save: "Сохранить",
        cancel: "Отмена",
        delete: "Удалить",
        edit: "Редактировать",
        logout: "Выйти",
        success: "Успех",
        error: "Ошибка",
        loading: "Загрузка...",
        expense_added: "Расход успешно добавлен",
        group_created: "Группа успешно создана",
        friend_added: "Друг успешно добавлен",
        profile_updated: "Профиль успешно обновлен"
    }
};

export function t(key) {
    const lang = localStorage.getItem('preferred_language') || navigator.language || 'en';
    // Try exact match first (e.g., 'zh-Hans')
    let dict = strings[lang];

    // If not found, try base language (e.g., 'zh' from 'zh-CN') - though for Chinese we want specific variants
    if (!dict) {
        const baseLang = lang.split('-')[0];
        dict = strings[baseLang];
    }

    // Default to English
    if (!dict) {
        dict = strings['en'];
    }

    return dict[key] || strings['en'][key] || key;
}
